language: node_js
sudo: false
compiler: g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "6.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-4.8
      - libnotify-bin
      - python3.5
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "node_modules"
before_script:
  - "virtualenv -p python3.5 ../venv"
  - "source ../bin/activate"
  - "pip install requirements.txt"
