language: python
python:
    - "3.4"

node_js:
    - "0.10"

rvm:
    - "2.2.1"

jdk:
    - "openjdk7"

before_install:
    - "sudo npm install -g grunt-cli"
    - "sudo rm -rf .npm"
    - "sudo gem install bundler --pre"

install:
    - "source ${SHIPPABLE_VE_DIR}/bin/activate"
    - "pip install -r requirements.txt"
    - "sudo npm install"
    - "npm run postinstall_CI"
    - "bundle install"
    - "deactivate"

script:
    - "source ${SHIPPABLE_VE_DIR}/bin/activate"
    - "echo \"Python version: $(python --version)\""
    - "echo \"NodeJS version: $(node --version)\""
    - "npm test"
    - "python manage.py test"
    - "deactivate"
