language: python
python:
  - "3.5"
env:
  global:
    - DISTRO=precise
cache:
  apt: true
  pip: true
  directories:
    - "${HOME}/.npm"
    - "node_modules"
addons:
  apt:
    sources:
      - sourceline: "deb-src https://deb.nodesource.com/node_6.x ${DISTRO} main"
        key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      - sourceline: "deb https://deb.nodesource.com/node_6.x ${DISTRO} main"
        key_url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    packages:
      - nodejs
before_install:
  - "npm install"
script:
  - "npm test"
